http:
  addr: ":8089"

db:
  dsn: "root:root@tcp(localhost:13316)/demo_user"

redis:
  addr: "localhost:6389"

etcd:
  endpoints:
    - "localhost:12379"

opentelemetry:
  serviceName: "demo"
  serviceVersion: "v0.0.1"

logger:
  filename: "d:\\appcache\\elasticsearch\\logs\\reward.log"
  maxsize: 50
  maxBackups: 3
  maxAge: 7

zipkin:
  collectorURL: "http://localhost:9411/api/v2/spans"

prometheus:
  listenPort: ":8081"

remoteProvider:
  provider: "etcd3"
  endpoint: "http://127.0.0.1:12379"
  path: "/reward"
